-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.advertisement_table
(
    ad_id uuid NOT NULL,
    offer_name character(120) COLLATE pg_catalog."default",
    offer_desc text COLLATE pg_catalog."default",
    offer_profile_desc text COLLATE pg_catalog."default",
    offer_language character(20) COLLATE pg_catalog."default",
    company_name character(60) COLLATE pg_catalog."default",
    company_type character(100) COLLATE pg_catalog."default",
    contract_type character(20) COLLATE pg_catalog."default",
    offer_work_type character(100) COLLATE pg_catalog."default",
    offer_location character(120) COLLATE pg_catalog."default",
    remote_work boolean,
    starting_date timestamp with time zone,
    salary_min real,
    salary_max real,
    company_pic bytea,
    work_pic bytea,
    reg_date timestamp with time zone,
    work_duration smallint,
    experience_years smallint,
    company_size smallint,
    CONSTRAINT advertisement_table_pkey PRIMARY KEY (ad_id)
);

COMMENT ON TABLE public.advertisement_table
    IS 'Table Annonces';

CREATE TABLE IF NOT EXISTS public.company_table
(
    company_id uuid NOT NULL,
    company_name character(120) COLLATE pg_catalog."default" NOT NULL,
    reg_date timestamp with time zone,
    siret character(14) COLLATE pg_catalog."default" NOT NULL,
    company_desc text COLLATE pg_catalog."default",
    n_employees smallint,
    hq_location character(600) COLLATE pg_catalog."default",
    work_sector character(240) COLLATE pg_catalog."default",
    company_mail text COLLATE pg_catalog."default",
    company_phone character(12) COLLATE pg_catalog."default",
    n_followers smallint,
    comapny_vip text COLLATE pg_catalog."default",
    comapny_pic bytea,
    comapny_social text COLLATE pg_catalog."default",
    comapny_type character(100) COLLATE pg_catalog."default",
    company_banner bytea,
    language character varying(40) COLLATE pg_catalog."default",
    CONSTRAINT company_table_pkey PRIMARY KEY (company_id)
);

COMMENT ON TABLE public.company_table
    IS 'Table info compagnie';

CREATE TABLE IF NOT EXISTS public.information_table
(
    ad_id uuid,
    company_id uuid,
    user_id uuid,
    post_name character(120) COLLATE pg_catalog."default",
    applicant character(60) COLLATE pg_catalog."default",
    company character(120) COLLATE pg_catalog."default",
    application_date timestamp with time zone,
    expertiselevel character(20) COLLATE pg_catalog."default"
);

CREATE TABLE IF NOT EXISTS public.user_table
(
    user_id uuid NOT NULL,
    firstname character(30) COLLATE pg_catalog."default",
    lastname character(30) COLLATE pg_catalog."default",
    user_pwd text COLLATE pg_catalog."default",
    age smallint,
    resume bytea,
    user_type character(3) COLLATE pg_catalog."default",
    wanter_work text COLLATE pg_catalog."default",
    location character(240) COLLATE pg_catalog."default",
    reg_date timestamp with time zone,
    user_email text COLLATE pg_catalog."default",
    user_phone character(12) COLLATE pg_catalog."default",
    user_website character(120) COLLATE pg_catalog."default",
    user_linkedin text COLLATE pg_catalog."default",
    user_social text COLLATE pg_catalog."default",
    newsletter boolean,
    CONSTRAINT user_table_pkey PRIMARY KEY (user_id)
);

COMMENT ON TABLE public.user_table
    IS 'Tableau Users (rechercheur d''emplois, recruteurs, admins)';

ALTER TABLE IF EXISTS public.advertisement_table
    ADD FOREIGN KEY (company_size)
    REFERENCES public.company_table (n_employees) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.advertisement_table
    ADD FOREIGN KEY (company_name)
    REFERENCES public.company_table (company_name) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.advertisement_table
    ADD FOREIGN KEY (company_type)
    REFERENCES public.company_table (comapny_type) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.information_table
    ADD CONSTRAINT "information_table_AdID_fkey" FOREIGN KEY (ad_id)
    REFERENCES public.advertisement_table (ad_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.information_table
    ADD CONSTRAINT "information_table_CompanyID_fkey" FOREIGN KEY (company_id)
    REFERENCES public.company_table (company_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.information_table
    ADD CONSTRAINT "information_table_UserID_fkey" FOREIGN KEY (user_id)
    REFERENCES public.user_table (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;